### ISSUE TITLE
rotary being able to spin past the stopper on low framerates. didn't fixed

### ISSUE THREAD

**Issue by habacksill** [CassCoffey/LethalPhones#29]
### Describe the bug

The rotary is still spinning 2 or more.

### Reproducible Test

mabye more than 4 player and custom moons?
i just open phone and rolled a rotary

**Comment by CassCoffey** [comment]
Would you be able to get a clip of this happening? Or a range of what framerates you were seeing. 
I'm having difficulty reproducing this locally.

**Comment by CassCoffey** [comment]
I've just pushed 1.3.0 to Thunderstore which should catch a few more edgecases at super low framerates. Let me know if it happens again after 1.3.0.

**Comment by superstrongbozo** [comment]
> Would you be able to get a clip of this happening? Or a range of what framerates you were seeing. I'm having difficulty reproducing this locally.

it still happens, with my experience it can happen with freeze or it can just do it without any lag, mostly in orbit
